packages:
  - apps/*
  - packages/*
  - tools/*

allowBuilds:
  '@google/genai': false
  esbuild: false
  msgpackr-extract: true
  protobufjs: false

catalogMode: prefer

catalog:
  vite-plus: 0.3.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
overrides:
  '@effect/opentelemetry': 4.0.0-rc.112
  '@effect/platform-node-shared': 4.0.0-rc.112
  effect: 4.0.0-rc.112
  vite: 'catalog:'
peerDependencyRules:
  allowAny: [vite, typescript]
  allowedVersions: {vite: '*', typescript: '*'}
minimumReleaseAgeExclude:
  - '@effect/atom-react@4.0.0-rc.108'
  - '@effect/opentelemetry@4.0.0-rc.108'
  - '@effect/platform-node-shared@4.0.0-rc.108'
  - '@effect/platform-node@4.0.0-rc.108'
  - '@effect/vitest@4.0.0-rc.108'
  - effect@4.0.0-rc.108
